### ISSUE TITLE
Typo in homepage text

### ISSUE THREAD

**Issue by wsedor** [nsmq-ai/nsmqai#65]
**Describe the bug**
2nd paragraph on homepage has `The goal of nsmqai is build`. It is missing a `to`

**To Reproduce**

1. Go to homepage
2. See second paragraph

**Expected behavior**

Text should read as `The goal of nsmqai is to build`

**Screenshots**
![image](https://github.com/nsmq-ai/nsmqai/assets/10053339/d7a9c52b-90c1-44ea-946e-9a9d7c39beb5)

**Comment by SaketKaswa20** [comment]
I can solve. Please assign me
