### ISSUE TITLE
Edit Readme to make it easier for users to run app

### ISSUE THREAD

**Issue by Nanayeb34** [nsmq-ai/nsmqai#71]
**Describe the bug**

The current Readme makes the assumption that all users have high level access to the ML models and notebooks being used.

 With the ML teams uploading a generic script for their work in their respective directories, the Readme should be edited to inform users on the steps to undertake(where to locate the ML notebooks, running all the notebooks and getting their respective API keys) in order to run the app. It can also provide detail on how to merge the notebooks for those who would like to have a single API for all the models. This way, users can contribute more easily to the project.

**Comment by kojomensahonums** [comment]
Yes that's true, good issue
